version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:4.1-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: adimroot
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq